### ISSUE TITLE
Code not compatible with current version of Adafruit_ZeroDMA

### ISSUE THREAD

**Issue by billpugh** [adafruit/Adafruit_Lightship#2]
The Adafruit_ZeroDMA library underwent a significant revision on Nov 16, 2017 which broke backwards compatibility. [The comment on the change](https://github.com/adafruit/Adafruit_ZeroDMA/commit/f106c5120b85d84bd052eb16d781ed9c1c2fe494#diff-766911a093de85f18ededdb9c744b5a0) said "All other Adafruit libraries using ZeroDMA have been updated to match." But Adafruit_Lightship wasn't updated.

**Comment by PaintYourDragon** [comment]
Fixed now. Sorry. Thank you for spotting that!
